# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    tags:
      - "v**"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache
        uses: actions/cache@v2.1.3
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Clone docs branch
        uses: actions/checkout@v2
        with:
          ref: docs
          path: __docs

      - name: Build
        run: |
          yarn
          yarn build

      - name: Commit and push
        run: |
          rm -rf __docs/*
          cp -r dist/* __docs/
          cd __docs
          git add .
          git config user.email "x.li.gem@gmail.com"
          git config user.name "Github CI Bot"
          git commit --amend -m "Site updated - `date '+%Y-%m-%d %H:%M:%S'`"
          git push -f